version: '3.8'

services:
  redis:
    image: redis:7.0-alpine
    container_name: my-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
